### ISSUE TITLE
On Job Search Results, only show the "More Info" button if the Job is posted directly to Jobs for Hope

### ISSUE THREAD

**Issue by entrotech** [hackforla/jobs-for-hope#153]
Then Modal should not include an IFrame (since there is no external site with the job posting details).  Modify the modal, or replace it with a seaprate page that shows the internal job information.

**Comment by nclairesays** [comment]
W

**Comment by nclairesays** [comment]
Woops sorry, did not mean to close this

**Comment by nclairesays** [comment]
I thought we decided to remove the modal completely for now?

**Comment by entrotech** [comment]
We could remove the button, but if we show it for internal job postings,
then we would have somewhere to display the additional info that can be
entered on the job posting form, like salary, and eventually a full
address, job requirements, etc. Like you say, it won't matter for an
initial demo, unless we want to show how to directly enter jobs in the
system.
