### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by histef** [hackforla/jobs-for-hope#25]
Need to create responsive About section(component).
design guide: https://projects.invisionapp.com/share/BTN6GLIJNUY#/screens/311697394

Guidelines:
-No need for the banner, as it will be a component.
-If anything, just the shell of the page would be great, we could have someone take care of the content later.
-here is where you can get the county seal (you can just copy/paste this in `src`: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Seal_of_Los_Angeles_County%2C_California.svg/215px-Seal_of_Los_Angeles_County%2C_California.svg.png"

Notes-you'll need to use Sass (particularly the variables from -variables.scss) for the About page

**Comment by clockwerkz** [comment]
Hey Stef, would you mind if I tried working on this issue?

**Comment by histef** [comment]
Hey @clockwerkz!

**Comment by histef** [comment]
Hey @clockwerkz let me know if you are working on this, if not, you can check out the other issue.

**Comment by histef** [comment]
as of 1/8/2019 @hanshank is assigned to this issue.
