### ISSUE TITLE
Banner component

### ISSUE THREAD

**Issue by histef** [hackforla/jobs-for-hope#26]
Need a Banner component.
design guide: https://projects.invisionapp.com/share/BTN6GLIJNUY#/screens/311697394

Guidelines:
-to be used in the Organizations, About, Contact pages
-should be responsive
-hardcoded contact banner is up (can use this as a reference)
-state handling should be done using Redux
-styling should be done in Sass(.scss file)
-need images for Org, and About banner-you can choose just use similar photos as in the design guide(subject to approval)-can use any free stock photos (ex. pexels.com or unsplash.com)

**Comment by hanshank** [comment]
I am working on this tonight!
