### ISSUE TITLE
Organization detail data

### ISSUE THREAD

**Issue by fyliu** [hackforla/jobs-for-hope#64]
Go to each agency and copy down several pieces of information into a spreadsheet
- name
- mission statement
- description
- location
- website
- logo url

**Comment by fyliu** [comment]
This is not necessary for the MVP. It was only created to support #62.

**Comment by entrotech** [comment]
What we probably want to do is add a form for the adminitrator to add/edit more detailed organization information interactively through the app.

**Comment by entrotech** [comment]
Still have two issues:
1. Some of the markup created by the draft.js implementation does not generate the correct Html (e.g., underlined text).
2. You cannot upload an image, but can only reference an image that the node server already has compiled into the build. Ultimately, it woudl be best to serve images from AWS S3 or the like.
