### ISSUE TITLE
Add a login/registration system

### ISSUE THREAD

**Issue by entrotech** [hackforla/jobs-for-hope#85]
To get set up for the application to allow data entry and maintenance of organizations and jobs, we need to allow users to register and login (anonymous users will still be able to search read-only information about jobs and organizations).  They will need to provide an email as a username and a password, stored in the postgres database in a logins table.  There needs to be two kinds of registered users. System administrators will be able to enter/edit all organizations and jobs.  Organization Representatives will only be able to enter/edit their own organization(s) and the associated jobs. I guess an organization rep might be assocated with more than one organization.

Once all this is set up, then we can lock down the Organization and Job create/edit forms so that only authorized users can see and run them.

**Comment by brianplynn** [comment]
all done (mostly) :)
